# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(786, 443)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.nickname_label = QtWidgets.QLabel(Form)
        self.nickname_label.setMinimumSize(QtCore.QSize(0, 110))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nickname_label.setFont(font)
        self.nickname_label.setObjectName("nickname_label")
        self.gridLayout.addWidget(self.nickname_label, 1, 0, 1, 1)
        self.password_label = QtWidgets.QLabel(Form)
        self.password_label.setMinimumSize(QtCore.QSize(0, 110))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.gridLayout.addWidget(self.password_label, 2, 0, 1, 1)
        self.enter_btn = QtWidgets.QPushButton(Form)
        self.enter_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.enter_btn.setFont(font)
        self.enter_btn.setObjectName("enter_btn")
        self.gridLayout.addWidget(self.enter_btn, 4, 0, 1, 2)
        self.error = QtWidgets.QLabel(Form)
        self.error.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.error.setFont(font)
        self.error.setText("")
        self.error.setObjectName("error")
        self.gridLayout.addWidget(self.error, 3, 0, 1, 2)
        self.nickname = QtWidgets.QLineEdit(Form)
        self.nickname.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nickname.setFont(font)
        self.nickname.setObjectName("nickname")
        self.gridLayout.addWidget(self.nickname, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 2)
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setText("")
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 1, 1, 1)
        self.previous_window = QtWidgets.QPushButton(Form)
        self.previous_window.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.previous_window.setFont(font)
        self.previous_window.setObjectName("previous_window")
        self.gridLayout.addWidget(self.previous_window, 6, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nickname_label.setText(_translate("Form", "Введите имя: "))
        self.password_label.setText(_translate("Form", "Введите пароль: "))
        self.enter_btn.setText(_translate("Form", "Войти"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\">Авторизация</p></body></html>"))
        self.previous_window.setText(_translate("Form", "Вернуться на начальное окно"))
