# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(610, 411)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.rename_btn = QtWidgets.QPushButton(Form)
        self.rename_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rename_btn.setFont(font)
        self.rename_btn.setObjectName("rename_btn")
        self.gridLayout.addWidget(self.rename_btn, 2, 1, 1, 1)
        self.players_list = QtWidgets.QListWidget(Form)
        self.players_list.setMinimumSize(QtCore.QSize(200, 280))
        self.players_list.setObjectName("players_list")
        self.gridLayout.addWidget(self.players_list, 0, 0, 6, 1)
        self.change_password_btn = QtWidgets.QPushButton(Form)
        self.change_password_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.change_password_btn.setFont(font)
        self.change_password_btn.setObjectName("change_password_btn")
        self.gridLayout.addWidget(self.change_password_btn, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.delete_btn = QtWidgets.QPushButton(Form)
        self.delete_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        self.delete_btn.setFont(font)
        self.delete_btn.setObjectName("delete_btn")
        self.gridLayout.addWidget(self.delete_btn, 4, 1, 1, 1)
        self.alterable_nickname = QtWidgets.QLineEdit(Form)
        self.alterable_nickname.setObjectName("alterable_nickname")
        self.gridLayout.addWidget(self.alterable_nickname, 1, 1, 1, 1)
        self.message = QtWidgets.QLabel(Form)
        self.message.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.message.setFont(font)
        self.message.setText("")
        self.message.setObjectName("message")
        self.gridLayout.addWidget(self.message, 11, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.rename_btn.setText(_translate("Form", "Переименовать"))
        self.change_password_btn.setText(_translate("Form", "Сменить пароль"))
        self.label.setText(_translate("Form", "Введите прозвище аккаунта\n"
" с которым хотите\n"
" взаимодействовать:"))
        self.delete_btn.setText(_translate("Form", "Удалить"))
