# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 295)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.error = QtWidgets.QLabel(Form)
        self.error.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.error.setFont(font)
        self.error.setText("")
        self.error.setObjectName("error")
        self.gridLayout.addWidget(self.error, 6, 0, 1, 2)
        self.new_password = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.new_password.setFont(font)
        self.new_password.setObjectName("new_password")
        self.gridLayout.addWidget(self.new_password, 1, 1, 1, 1)
        self.confirm_new_password = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confirm_new_password.setFont(font)
        self.confirm_new_password.setObjectName("confirm_new_password")
        self.gridLayout.addWidget(self.confirm_new_password, 2, 1, 1, 1)
        self.accept_btn = QtWidgets.QPushButton(Form)
        self.accept_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.accept_btn.setFont(font)
        self.accept_btn.setObjectName("accept_btn")
        self.gridLayout.addWidget(self.accept_btn, 3, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Введите пароль:"))
        self.label_3.setText(_translate("Form", "Подтвердите новый пароль:"))
        self.label_2.setText(_translate("Form", "Введите новый пароль:"))
        self.accept_btn.setText(_translate("Form", "OK"))
